import Head from 'next/head'
import { API_POST } from 'constants/apiPath'
import { getUrl } from 'utils'
import { PostCard } from 'components'
import styles from './styles.module.scss'

export default function PostPage({ data }) {
  return (
    <div>
      <Head>
        <title>POST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {
          data.map(item => {
            return (
              <PostCard key={item.id} id={item.id} href={item.href} title={item.title}>
                {item.content}
              </PostCard>
            )
          })
        }
      </div>
    </div>
  )
}

PostPage.getInitialProps = async (ctx) => {
  const path = getUrl(ctx, API_POST);
  const res = await fetch(path);
  const json = await res.json();
  const { data } = json;

  return { data };
}
