import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { Button, ComponentLabel, Input } from '../../components'
import { getCookie, setCookie } from '../utils'

export default function Login() {
  const [account, setAccount] = useState('admin')
  const [password, setPassword] = useState('admin')
  const [errorMsg, setErrorMsg] = useState('')
  const router = useRouter()

  useEffect(() => {
    const userNameCookie = getCookie('userName');
    if (userNameCookie) {
      router.push('/')
    }
  }, []);

  const handleLogin = () => {
    setErrorMsg('');

    const requestBody = {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        account,
        password
      })
    };

    fetch('http://localhost:3000/api/login', requestBody)
      .then(response => response.json())
      .then(res => {
        const { name } = res;
        if (name) {
          setCookie('userName', name);
          router.reload();
        } else {
          setErrorMsg('Username or password is incorrect')
        }
      });
  }

  const handleEnter = (event) => {
    if (event.key === "Enter") {
      // Cancel the default action, if needed
      event.preventDefault();
      handleLogin();
    }
  }

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <center>
          <h1>Sign in</h1>

          <div style={{ width: 300 }}>
            <ComponentLabel label="User Name">
              <Input
                value={account}
                onChange={e => setAccount(e.target.value)}
                placeholder="admin"
                onKeyDown={handleEnter}
              />
            </ComponentLabel>

            <ComponentLabel label="Password">
              <Input
                value={password}
                onChange={e => setPassword(e.target.value)}
                placeholder="admin"
                onKeyDown={handleEnter}
              />
            </ComponentLabel>
          </div>

          <div>
            <Button onClick={handleLogin}>Sign in</Button>
          </div>

          <div style={{ color: 'red' }}>
            {errorMsg}
          </div>
        </center>
      </div>
    </div>
  )
}