import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { setCookie } from '../utils'

export default function Login() {
  const [account, setAccount] = useState('')
  const [password, setPassword] = useState('')
  const [errorMsg, setErrorMsg] = useState('')
  const router = useRouter()

  const handleLogin = () => {
    setErrorMsg('');

    const requestBody = {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        account,
        password
      })
    };

    fetch('http://localhost:3000/api/login', requestBody)
      .then(response => response.json())
      .then(res => {
        const { account } = res;
        if (account) {
          setCookie('user', account);
          router.push('/');
        } else {
          setErrorMsg('Username or password is incorrect')
        }
      });
  }

  const handleEnter = (event) => {
    if (event.key === "Enter") {
      // Cancel the default action, if needed
      event.preventDefault();
      handleLogin();
    }
  }

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <center>
          <h1>Login</h1>

          <div>
            User Name:
            <input
              value={account}
              onChange={e => setAccount(e.target.value)}
              placeholder="admin"
              onKeyDown={handleEnter}
            />
          </div>
          <div>
            Password:
            <input
              value={password}
              onChange={e => setPassword(e.target.value)}
              placeholder="admin"
              onKeyDown={handleEnter}
            />
          </div>
          <div style={{ color: 'red' }}>
            {errorMsg}
          </div>
          <div>
            <button onClick={handleLogin}>Login</button>
          </div>
        </center>
      </div>
    </div>
  )
}
