import Head from 'next/head'
import { API_FETCH_API } from 'constants/apiPath'

export default function FetchAPI({ data }) {
  return (
    <div>
      <Head>
        <title>Fetch API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <center>
          <h1>Data get from server</h1>
          <p>Name: {data.name}</p>
        </center>
      </div>
    </div>
  )
}

FetchAPI.getInitialProps = async (ctx) => {
  const res = await fetch(API_FETCH_API)
  const json = await res.json()
  return { data: json }
}
