import Head from 'next/head'
import Link from 'next/link'

export default function FetchAPI({ data }) {
  // console.log(data);
  return (
    <div>
      <Head>
        <title>Fetch API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href="/">
          <a>
            Back Home
          </a>
        </Link>

        <center>
          <h1>Data get from server</h1>
          <p>Name: {data.name}</p>
        </center>
      </div>
    </div>
  )
}

FetchAPI.getInitialProps = async (ctx) => {
  const res = await fetch('http://localhost:3000/api/fetch-api')
  const json = await res.json()
  return { data: json }
}
