import Head from 'next/head'
import { API_POST } from 'constants/apiPath'
import { getUrl } from 'utils'
import styles from './styles.module.scss'

export default function DetailPost({ data }) {
  const { title = 'Title', content = 'Content' } = data || {};

  return (
    <div>
      <Head>
        <title>Detail Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {
          data ? (
            <>
              <center><h2>{title}</h2></center>
              <p>{content}</p>
            </>
          ) : (
            <center>
              <div>
                This post does not exist
              </div>
            </center>
          )
        }

      </div>
    </div>
  )
}

DetailPost.getInitialProps = async (ctx) => {
  const { query } = ctx;
  const { id } = query || {}
  const path = getUrl(ctx, API_POST) + `?${id}`;

  const res = await fetch(path, {
    method: 'GET',
    headers: { 'Content-Type': 'application/json' },
  });

  const json = await res.json();
  const { data } = json;

  return { data };
}
