import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'

export default function Router() {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Router</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href="/">
          <a>
            Back Home
          </a>
        </Link>

        <center>
          <h1>Router</h1>

          <button
            type="button"
            onClick={() => {
              router.push({
                pathname: '/router/router-1/',
                query: { id: '1' },
              })
            }}
          >
            Go to Router 1
          </button>
        </center>
      </div>
    </div>
  )
}
