import Head from 'next/head'
import Image from 'next/image'
import { Card } from 'components'
import styles from 'styles/Home.module.scss'
import { ROUTER_PATH } from 'constants/routerPath'
import config from 'package.json';

export default function Home() {
  const { name, version } = config || {};
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Card href={ROUTER_PATH.HELLO_WORLD} title="Hello World" />

          <Card href={ROUTER_PATH.FETCH_API} title="Fetch API" />

          <Card href={ROUTER_PATH.ROUTER} title="Router" />

          <Card href={ROUTER_PATH.POST} title="POST" />
        </div>
      </main>

      <footer className={styles.footer}>
        <a rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <span className={styles.version}>{`${name}`.toUpperCase() + ` / v${version}`}</span>
      </footer>
    </div>
  )
}
