import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { Button, Card } from '../components'
import styles from '../styles/Home.module.scss'
import { setCookie } from './utils'

export default function Home({ userName }) {
  const router = useRouter()

  const handleLogout = () => {
    setCookie('userName', '')
    router.push('/login')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.header}>
        <Image src="/user.png" alt="User Logo" width={24} height={24} />
        <span className={styles.user}>{userName}</span>
        <Button onClick={handleLogout}>Logout</Button>
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Card href="/hello-world" title="Hello World" />

          <Card href="/fetch-api" title="Fetch API" />

          <Card href="/router" title="Router" />
        </div>
      </main>

      <footer className={styles.footer}>
        <a rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
