import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="/hello-world">
            <a className={styles.card}>
              <h2>Hello World</h2>
              <p>Click to view page details</p>
            </a>
          </Link>

          <Link href="/fetch-api">
            <a className={styles.card}>
              <h2>Fetch API</h2>
              <p>Click to view page details</p>
            </a>
          </Link>

          <Link href="/router">
            <a className={styles.card}>
              <h2>Router</h2>
              <p>Click to view page details</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
