import Head from 'next/head'
import Link from 'next/link'

export default function HelloWorld() {
  return (
    <div>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href="/">
          <a>
            Back Home
          </a>
        </Link>

        <center>
          <h1>Hello world</h1>
        </center>
      </div>
    </div>
  )
}
